# Change these first
owner: Mimexe # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: Site
    url: https://mimedev.fr
  - name: Documentation
    url: https://docs.mimedev.fr
  - name: MimeHeberg
    url: https://panel.mimedev.fr
  - name: Téléchargements
    url: https://dl.mimedev.fr
  - name: Maven
    url: https://repo.mimedev.fr
  - name: MimeHeberg Node
    url: node.mimedev.fr
    port: 8080
    check: "tcp-ping"
#  - name: Commandes
#    url: play.mimedev.fr
#    port: 25565
#    check: "tcp-ping"

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.mimedev.fr
  # baseUrl: /your-repo-name
  theme: dark
  logoUrl: https://mimedev.fr/logo.png
  favicon: https://mimedev.fr/favicon.ico
  name: Mime Developpement
  introTitle: "Page de status de Mime Developpement."
  introMessage: Bienvenue sur la page de status de Mime Developpement, alimenté par GitHub et Upptime.
  navbar:
    - title: Site principal
      href: https://mimedev.fr
    - title: Discord
      href: https://discord.gg/rpbz5UKHZq
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER

i18n:
  activeIncidents: Incidents actifs
  allSystemsOperational: Tout est opérationnel
  incidentReport: "Incident #$NUMBER →"
  activeIncidentSummary: Ouvert le $DATE avec $POSTS posts
  incidentTitle: Incident $NUMBER détails
  incidentDetails: Détails de l''incident
  incidentFixed: Terminé
  incidentOngoing: En cours
  incidentOpenedAt: Ouvert à
  incidentClosedAt: Fermé à
  incidentViewOnGitHub: Regarder sur GitHub
  incidentCommentSummary: Posté le $DATE par $AUTHOR
  incidentBack: ← Retour
  pastIncidents: Incidents passés
  pastIncidentsResolved: Résolvé $MINUTES minutes avec $POSTS posts
  liveStatus: Statut en direct
  overallUptime: "Uptime de disponibilité globale: $UPTIME"
  overallUptimeTitle: Uptime de disponibilité globale
  averageResponseTime: "Temps de réponse moyen: $TIMEms"
  averageResponseTimeTitle: Réponse moyen
  sevelDayResponseTime: Temps de réponse de 7 jours
  responseTimeMs: Temps de réponse (ms)
  up: En ligne
  down: Hors ligne
  degraded: Degradé
  ms: ms
  loading: Chargement
  navGitHub: GitHub
  footer: Alimenté par Upptime
  rateLimitExceededTitle: Limite de débit dépassée
  rateLimitExceededIntro: Vous avez dépassé le nombre de requêtes autorisées par heure. Vous devez attendre avant d'accéder à nouveau à ce site. Vous pouvez également ajouter un jeton d'accès personnel GitHub pour continuer à utiliser ce site.
  rateLimitExceededWhatDoesErrorMean: Que signifie cette erreur ?
  rateLimitExceededErrorMeaning: Ce site utilise l’API GitHub pour accéder en temps réel au statut de nos sites. Par défaut, GitHub autorise chaque adresse IP à effectuer 60 requêtes par heure, ce que vous avez dépassé.
  rateLimitExceededErrorHowCanFix: Comment puis-je résoudre ce problème ?
  rateLimitExceededErrorFix: Vous pouvez attendre une heure pour que la limite de votre adresse IP soit réinitialisée. Alternativement, vous pouvez ajouter un jeton d'accès personnel GitHub, qui vous permet d'effectuer jusqu'à 5 000 requêtes par heure.
  rateLimitExceededGeneratePAT: Apprenez à générer un jeton d’accès personnel
  rateLimitExceededHasSet: Vous avez défini un jeton d'accès personnel.
  rateLimitExceededRemoveToken: Supprimer le jeton
  rateLimitExceededGitHubPAT: Jeton d'accès personnel GitHub
  rateLimitExceededCopyPastePAT: Copiez et collez votre jeton
  rateLimitExceededSaveToken: Enregistrer le jeton
  errorTitle: Une erreur s'est produite
  errorIntro: Une erreur est survenue lors de la récupération des dernières informations de statut.
  errorText: Vous pouvez réessayer dans quelques instants.
  errorHome: Aller à la page d’accueil
  pastScheduledMaintenance: Maintenances planifiées passées
  scheduledMaintenance: Maintenance planifiée
  scheduledMaintenanceSummaryStarted: Commencée le $DATE pour $DURATION minutes
  scheduledMaintenanceSummaryStarts: Commence le $DATE pour $DURATION minutes
  startedAt: Commencée le
  startsAt: Commence le
  duration: Durée
  durationMin: $DURATION minutes
  incidentCompleted: Terminée
  incidentScheduled: Planifiée
  duration24H: 24h
  duration7D: 7j
  duration30D: 30j
  duration1Y: 1a
  durationAll: tout
  locale: fr-FR

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
assignees:
  - Mimexe
